name: Actions

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  run-tests:
    name: Run Tracer Utils tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16"
      - run: npm install
      - run: npm test
